<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <DefineConstants>$(DefineConstants);_WIN64</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <DefineConstants>$(DefineConstants);_WIN64</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.9" />
		<PackageReference Include="dotNetRdf" Version="3.5.1" />
	</ItemGroup>

	<ItemGroup>
		<None Update="IFC2RDF\ifc2rdf-1.4.7-shaded.jar">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="ifcengine.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="libifcengine.so">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\IDS\20251009025325_Requirements-openBIM-building-permit-City-of-Vienna-entity-based-Specifications-v1-3.ids">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\IDS\IDS Ruimten voor Kievietsweg v001.ids">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\IDS\IDS voor Omgevingswet Ruimten v1.1.ids">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\IDS\IDS_for_LoGeRef_50_Georeferencing.ids">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\IDS\ILS voor ruimten in de omgevingswet-v1.1.ids">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\IDS\ILS_VOOR_RUIMTE_IN_DE_OMGEVINGSWET 4.2.2.ids">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\IDS\Omgevingswet-Ruimten-0.2.0.ids">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\IDS\VDCbase-KEU-ZZ-ZZZ-RG-TOTAL-XX-0001-InformationDeliverySpecification.ids">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\SHACL\ValidateBBoxes-IfcWall.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\SHACL\ValidateHeight.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\SHACL\ValidateModelBBoxes.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\SHACL\ValidateBBoxes.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\SHACL\ValidateTopologicalRelations.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\SPARQL\InsertTopologicalRelations-IfcWall-IfcRoof.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\SPARQL\InsertTopologicalRelations.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\SPARQL\InsertProjections.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\SPARQL\InsertBBoxes.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\SPARQL\InsertAreas.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\Workflows\vng_workflow_embedded-1.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\Workflows\vng_workflow_embedded-10.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\Workflows\vng_workflow_embedded-11.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\Workflows\vng_workflow_embedded-12.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\Workflows\vng_workflow_embedded-13.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\Workflows\vng_workflow_embedded-14.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\Workflows\vng_workflow_embedded-15.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\Workflows\vng_workflow_embedded-16.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\Workflows\vng_workflow_embedded-17.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\Workflows\vng_workflow_embedded-2.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\Workflows\vng_workflow_embedded-3.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\Workflows\vng_workflow_embedded-4.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\Workflows\vng_workflow_embedded-5.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\Workflows\vng_workflow_embedded-6.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\Workflows\vng_workflow_embedded-7.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\Workflows\vng_workflow_embedded-8.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\Workflows\vng_workflow_embedded-9.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Services\" />
	</ItemGroup>

</Project>
