<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <DefineConstants>$(DefineConstants);_WIN64</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <DefineConstants>$(DefineConstants);_WIN64</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.9" />
		<PackageReference Include="dotNetRdf" Version="3.5.1" />
	</ItemGroup>

	<ItemGroup>
		<None Update="IFC2RDF\ifc2rdf-1.4.7-shaded.jar">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="ifcengine.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="libifcengine.so">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\Workflows\vng_workflow1.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="SeedData\Workflows\vng_workflow2.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Services\" />
	</ItemGroup>

</Project>
